export const LANGUAGES = [
  { property: "EN-GB", label: "英語(イギリス)" },
  { property: "EN-US", label: "英語(アメリカ)" },
  { property: "FR", label: "フランス語" },
  { property: "ZH", label: "中国語" },
  { property: "ES", label: "スペイン語" },
  { property: "RU", label: "ロシア語" },
  { property: "DE", label: "ドイツ語" },
  { property: "IT", label: "イタリア語" },
  { property: "PT-PT", label: "ポルトガル語（ポルトガル）" },
  { property: "PT-BR", label: "ポルトガル語(ブラジル)" },
  { property: "CS", label: "チェコ語" },
  { property: "DA", label: "デンマーク語" },
  { property: "NL", label: "オランダ語" },
  { property: "PL", label: "ポーランド語" },
  { property: "BG", label: "ブルガリア語" },
  { property: "EL", label: "ギリシャ語" },
  { property: "ET", label: "エストニア語" },
  { property: "FI", label: "フィンランド語" },
  { property: "HU", label: "ハンガリー語" },
  { property: "LT", label: "リトアニア語" },
  { property: "LV", label: "ラトビア語" },
  { property: "RO", label: "ルーマニア語" },
  { property: "SK", label: "スロヴァキア語" },
  { property: "SL", label: "スロベニア語" },
  { property: "SV", label: "スウェーデン語" },
];
