require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  TargetRailsVersion: 6.0.4
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'


Style/Documentation:
  Enabled: false

